### PR TITLE
Fix SNP export

### PR DESCRIPTION
**Pull request by mirasrael**
When SNP node selected then Export page fails because export metadata format was changed. Also exporters for SNP data formats doesn't work with latest database structure. This fix requires changes in transmart-core-db (https://github.com/transmart/transmart-core-db/pull/37)

### CODE REVIEW

**Comment by Terry-Weymouth** [comment]
What is the status on the pull request? (When was it last updated?)

**Comment by mirasrael** [comment]
It wasn't updated since Jul 28. Its awaiting when pull request in transmart-core-db will be accepted. But nothing what I can do to force this. (No questions or comments about the pull request).

**Comment by Terry-Weymouth** [comment]
@mirasrael Could you check on the travis failure and let me know what that is about. It would be nice to get this green before committing. Thanks.

**Comment by mirasrael** [comment]
The travis failure doesn't look related to content of pull request, but I re-based all changes on top of current master for transmart-core-db and transmartApp.

**Pull request merged**
